springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

TILGANGSMASKINEN_SCOPE: prod-gcp.tilgangsmaskin.populasjonstilgangskontroll

FPSAK_SCOPE: prod-fss.teamforeldrepenger.fpsak
FPSAK_BASE_URL: https://fpsak-api.prod-fss-pub.nais.io

ENTRA_PROXY_SCOPE: prod-gcp.sikkerhetstjenesten.entra-proxy

PDL_BASE_URL: https://pdl-api.prod-fss-pub.nais.io/graphql
PDL_SCOPE: prod-fss.pdl.pdl-api

NOM_BASE_URL: https://nom-api.intern.nav.no/graphql
NOM_SCOPE: prod-gcp.nom.nom-api

SKJERMING_PIP_SCOPE: prod-gcp.nom.skjermede-personer-pip

KABAL_API_SCOPE: prod-gcp.klage.kabal-api

REGOPPSLAG_URL: https://regoppslag.prod-fss-pub.nais.io
REGOPPSLAG_SCOPE: prod-fss.teamdokumenthandtering.regoppslag

TENANT_ID: 62366534-1ec3-4962-8869-9b5535279d0b