springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

TILGANGSMASKINEN_SCOPE: dev-gcp.tilgangsmaskin.populasjonstilgangskontroll

FPSAK_SCOPE: dev-fss.teamforeldrepenger.fpsak
FPSAK_BASE_URL: https://fpsak-api.dev-fss-pub.nais.io

ENTRA_PROXY_SCOPE: dev-gcp.sikkerhetstjenesten.entra-proxy

PDL_BASE_URL: https://pdl-api.dev-fss-pub.nais.io/graphql
PDL_SCOPE: dev-fss.pdl.pdl-api

NOM_BASE_URL: https://nom-api.intern.dev.nav.no/graphql
NOM_SCOPE: dev-gcp.nom.nom-api

SKJERMING_PIP_SCOPE: dev-gcp.nom.skjermede-personer-pip

KABAL_API_SCOPE: dev-gcp.klage.kabal-api

TENANT_ID: 966ac572-f5b7-4bbe-aa88-c76419c0f851